// Detailed offer data for the Connect page Database tab
export const offersByEmployer: { [key: string]: any[] } = {
  'Cravath, Swaine & Moore': [
    { 
      id: 1, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 15000, 
      perks: 'Housing stipend, all meals covered', 
      accepted: true,
      applicationDate: 'August 15, 2024',
      interviewDate: 'September 10, 2024',
      offerDate: 'September 25, 2024',
      responseDate: 'October 2, 2024',
      interviewProcess: '3 rounds: Initial screening (30 min), Partner interview (45 min), Final callback (2 hours with 4 partners)',
      interviewFormat: 'Mix of behavioral and case-based questions. Heavy focus on M&A deal experience and attention to detail.',
      applicantInformation: 'GPA: 3.85 | Class Year: 2L | Law Review | Previously worked as paralegal at boutique M&A firm | Strong interest in corporate law and private equity transactions',
      additionalNotes: 'Very collegial atmosphere during interviews. All partners were friendly and answered questions honestly about work-life balance.',
      position: 'Summer Associate',
      classYear: '2L',
      school: 'Harvard Law School'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 15000, 
      perks: 'Housing stipend, all meals covered', 
      accepted: true,
      applicationDate: 'August 18, 2024',
      interviewDate: 'September 12, 2024',
      offerDate: 'September 27, 2024',
      responseDate: 'October 5, 2024',
      interviewProcess: '2 rounds: Coffee chat with associate (informal), Callback with 3 partners',
      interviewFormat: 'Behavioral questions focused on teamwork and handling pressure. Some hypothetical deal scenarios.',
      applicantInformation: 'GPA: 3.92 | Class Year: 2L | Moot Court | Background in finance (worked at Goldman Sachs for 2 years before law school)',
      additionalNotes: 'They seemed genuinely interested in getting to know me as a person, not just my resume.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 15000, 
      perks: 'Housing stipend, meals', 
      accepted: true,
      applicationDate: 'August 20, 2024',
      interviewDate: 'September 15, 2024',
      offerDate: 'September 28, 2024',
      responseDate: 'October 3, 2024',
      interviewProcess: '3 rounds: Phone screen, Virtual interview with 2 associates, In-person callback',
      interviewFormat: 'Mix of technical legal questions and personality fit. Asked about specific deals from resume.',
      applicantInformation: 'GPA: 3.75 | Class Year: 2L | Journal of International Law Editor | Undergraduate degree in Economics from Yale',
      additionalNotes: 'Received offer same day as callback. Very efficient process.',
      position: 'Summer Associate',
      classYear: '2L',
      school: 'Yale Law School'
    },
    { 
      id: 4, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 15000, 
      perks: 'Housing assistance', 
      accepted: false,
      applicationDate: 'August 22, 2024',
      interviewDate: 'September 18, 2024',
      offerDate: 'September 30, 2024',
      responseDate: 'October 7, 2024',
      interviewProcess: '2 rounds: Initial interview, Callback with 5 partners',
      interviewFormat: 'Heavy emphasis on writing sample discussion and hypothetical client scenarios.',
      additionalNotes: 'Declined in favor of West Coast firm for geographic reasons.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 15000, 
      perks: 'Full housing support', 
      accepted: true,
      applicationDate: 'August 25, 2024',
      interviewDate: 'September 20, 2024',
      offerDate: 'October 1, 2024',
      responseDate: 'October 8, 2024',
      interviewProcess: '4 rounds: Coffee chat, Associate interview, Partner interview, Final managing partner meeting',
      interviewFormat: 'Very conversational. Focus on culture fit and long-term career goals.',
      additionalNotes: 'Managing partner personally called to extend offer. Made me feel very valued.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'Sullivan & Cromwell': [
    { 
      id: 1, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 12000, 
      perks: 'Housing assistance', 
      accepted: true,
      applicationDate: 'August 10, 2024',
      interviewDate: 'September 5, 2024',
      offerDate: 'September 20, 2024',
      responseDate: 'September 28, 2024',
      interviewProcess: '2 rounds: Screening interview with recruiting, Callback with 4 partners',
      interviewFormat: 'Mix of behavioral and technical questions. Discussion of recent corporate law developments.',
      additionalNotes: 'Very impressed by the quality of work and client base. Partners were brilliant.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 12000, 
      perks: 'Housing stipend', 
      accepted: true,
      applicationDate: 'August 12, 2024',
      interviewDate: 'September 8, 2024',
      offerDate: 'September 22, 2024',
      responseDate: 'September 30, 2024',
      interviewProcess: '3 rounds: Phone screen, Virtual panel, In-person callback',
      interviewFormat: 'Competency-based questions. Asked about teamwork, leadership, and handling difficult situations.',
      additionalNotes: 'Everyone I met emphasized the firm\'s training program and mentorship culture.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'Washington, DC', 
      salary: 225000, 
      bonus: 12000, 
      perks: 'Relocation assistance', 
      accepted: true,
      applicationDate: 'August 14, 2024',
      interviewDate: 'September 10, 2024',
      offerDate: 'September 24, 2024',
      responseDate: 'October 1, 2024',
      interviewProcess: '2 rounds: Initial interview, Callback with DC office partners',
      interviewFormat: 'Focus on regulatory and government work experience. Discussion of policy interests.',
      additionalNotes: 'DC office has great work-life balance compared to NYC. Partners left by 7pm.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 12000, 
      perks: 'Housing assistance', 
      accepted: false,
      applicationDate: 'August 16, 2024',
      interviewDate: 'September 12, 2024',
      offerDate: 'September 26, 2024',
      responseDate: 'October 4, 2024',
      interviewProcess: '3 rounds: Phone screen, Associate interview, Partner callback',
      interviewFormat: 'Standard behavioral questions. Some case studies on client management.',
      additionalNotes: 'Great firm but chose a competitor with better practice group fit.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'Washington, DC', 
      salary: 225000, 
      bonus: 12000, 
      perks: 'Housing support', 
      accepted: true,
      applicationDate: 'August 19, 2024',
      interviewDate: 'September 14, 2024',
      offerDate: 'September 28, 2024',
      responseDate: 'October 6, 2024',
      interviewProcess: '2 rounds: Video interview, Full-day callback',
      interviewFormat: 'In-depth discussion of writing sample. Questions about specific practice area interests.',
      additionalNotes: 'Impressed by the diversity of practice groups and flexibility in choosing assignments.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'Latham & Watkins': [
    { 
      id: 1, 
      location: 'Los Angeles, CA', 
      salary: 225000, 
      bonus: 8000, 
      perks: 'Relocation assistance', 
      accepted: true,
      applicationDate: 'July 28, 2024',
      interviewDate: 'August 25, 2024',
      offerDate: 'September 10, 2024',
      responseDate: 'September 18, 2024',
      interviewProcess: '3 rounds: Phone screen, Associate panel, Partner callback',
      interviewFormat: 'Focus on entertainment and tech law interests. Casual, California vibe.',
      additionalNotes: 'LA office has amazing client work in entertainment industry. Partners know everyone.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 8000, 
      perks: 'Housing stipend', 
      accepted: true,
      applicationDate: 'July 30, 2024',
      interviewDate: 'August 28, 2024',
      offerDate: 'September 12, 2024',
      responseDate: 'September 20, 2024',
      interviewProcess: '2 rounds: Initial screening, Full callback with 5 attorneys',
      interviewFormat: 'Mix of behavioral and situational questions. Very friendly interviewers.',
      additionalNotes: 'Large summer associate class means good networking and social events.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'Los Angeles, CA', 
      salary: 225000, 
      bonus: 8000, 
      perks: 'Relocation support', 
      accepted: true,
      applicationDate: 'August 1, 2024',
      interviewDate: 'August 30, 2024',
      offerDate: 'September 14, 2024',
      responseDate: 'September 22, 2024',
      interviewProcess: '3 rounds: Coffee chat, Video interview, In-person callback',
      interviewFormat: 'Conversational style. Interested in hobbies and personal interests beyond law.',
      additionalNotes: 'Great culture. Associates genuinely seemed happy to be there.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'Chicago, IL', 
      salary: 225000, 
      bonus: 8000, 
      perks: 'Housing assistance', 
      accepted: false,
      applicationDate: 'August 3, 2024',
      interviewDate: 'September 1, 2024',
      offerDate: 'September 16, 2024',
      responseDate: 'September 24, 2024',
      interviewProcess: '2 rounds: Phone screen, Callback with Chicago partners',
      interviewFormat: 'Standard interview questions. Focus on Midwest ties and commitment to region.',
      additionalNotes: 'Chose to stay on East Coast for family reasons.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 8000, 
      perks: 'Relocation package', 
      accepted: true,
      applicationDate: 'August 5, 2024',
      interviewDate: 'September 3, 2024',
      offerDate: 'September 18, 2024',
      responseDate: 'September 26, 2024',
      interviewProcess: '4 rounds: Screening, Associate panel, Partner interview, Final meeting with practice group head',
      interviewFormat: 'Technical questions about corporate law. Discussion of deal structures.',
      additionalNotes: 'Practice group head was very engaged and provided detailed overview of typical assignments.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 6, 
      location: 'Los Angeles, CA', 
      salary: 225000, 
      bonus: 8000, 
      perks: 'Housing support', 
      accepted: true,
      applicationDate: 'August 7, 2024',
      interviewDate: 'September 5, 2024',
      offerDate: 'September 19, 2024',
      responseDate: 'September 27, 2024',
      interviewProcess: '2 rounds: Video call, In-person callback',
      interviewFormat: 'Very laid-back. Focus on culture fit and interest in firm\'s pro bono work.',
      additionalNotes: 'Impressed by commitment to pro bono and public interest work.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'Skadden, Arps': [
    { 
      id: 1, 
      location: 'Boston, MA', 
      salary: 225000, 
      bonus: 10000, 
      perks: 'Bar study stipend', 
      accepted: true,
      applicationDate: 'August 8, 2024',
      interviewDate: 'September 2, 2024',
      offerDate: 'September 17, 2024',
      responseDate: 'September 25, 2024',
      interviewProcess: '3 rounds: Phone screen, Associate interview, Partner callback',
      interviewFormat: 'Mix of behavioral and technical. Asked about litigation vs. transactional interests.',
      additionalNotes: 'Boston office is smaller and tight-knit. Everyone knows each other.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 10000, 
      perks: 'Housing assistance', 
      accepted: true,
      applicationDate: 'August 10, 2024',
      interviewDate: 'September 4, 2024',
      offerDate: 'September 19, 2024',
      responseDate: 'September 27, 2024',
      interviewProcess: '2 rounds: Initial interview, Callback with litigation group',
      interviewFormat: 'Heavy focus on writing ability and oral advocacy. Discussed moot court experience.',
      additionalNotes: 'Litigation group is top-notch. Associates get real courtroom experience early.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'Boston, MA', 
      salary: 225000, 
      bonus: 10000, 
      perks: 'Bar study stipend, housing', 
      accepted: true,
      applicationDate: 'August 12, 2024',
      interviewDate: 'September 6, 2024',
      offerDate: 'September 21, 2024',
      responseDate: 'September 29, 2024',
      interviewProcess: '3 rounds: Coffee chat, Video interview, Full-day callback',
      interviewFormat: 'Conversational but thorough. Questions about teamwork and handling criticism.',
      additionalNotes: 'Bar study stipend is generous. Firm really invests in summer associate success.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 10000, 
      perks: 'Relocation support', 
      accepted: false,
      applicationDate: 'August 14, 2024',
      interviewDate: 'September 8, 2024',
      offerDate: 'September 23, 2024',
      responseDate: 'October 1, 2024',
      interviewProcess: '2 rounds: Phone screen, Callback',
      interviewFormat: 'Standard questions. Some case studies on client conflicts.',
      additionalNotes: 'Chose another firm with better pro bono opportunities.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'Boston, MA', 
      salary: 225000, 
      bonus: 10000, 
      perks: 'Bar stipend', 
      accepted: true,
      applicationDate: 'August 16, 2024',
      interviewDate: 'September 10, 2024',
      offerDate: 'September 25, 2024',
      responseDate: 'October 3, 2024',
      interviewProcess: '3 rounds: Initial screen, Associate panel, Partner interviews',
      interviewFormat: 'Focus on academic background and specific coursework. Asked about favorite classes.',
      additionalNotes: 'Partners were genuinely interested in teaching and mentoring. Great training program.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'Kirkland & Ellis': [
    { 
      id: 1, 
      location: 'Chicago, IL', 
      salary: 225000, 
      bonus: 11000, 
      perks: 'Housing assistance', 
      accepted: true,
      applicationDate: 'July 25, 2024',
      interviewDate: 'August 22, 2024',
      offerDate: 'September 8, 2024',
      responseDate: 'September 16, 2024',
      interviewProcess: '2 rounds: Phone screen, Callback with 6 attorneys',
      interviewFormat: 'Fast-paced interview. Questions about handling multiple deadlines and pressure.',
      applicantInformation: 'GPA: 3.88 | Class Year: 2L | Business Law Journal | From Chicago, familiar with local legal market | Strong interest in private equity',
      additionalNotes: 'Largest firm I interviewed with. Lots of resources and support systems.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 11000, 
      perks: 'Relocation package', 
      accepted: true,
      applicationDate: 'July 27, 2024',
      interviewDate: 'August 24, 2024',
      offerDate: 'September 10, 2024',
      responseDate: 'September 18, 2024',
      interviewProcess: '3 rounds: Initial screen, Practice group interview, Final callback',
      interviewFormat: 'Technical questions about PE and M&A. Discussion of deal experience.',
      applicantInformation: 'GPA: 3.91 | Class Year: 2L | Top 5% of class | MBA from Wharton before law school | Deep background in finance and M&A transactions',
      additionalNotes: 'PE practice is unmatched. If you want private equity experience, this is the place.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'Los Angeles, CA', 
      salary: 225000, 
      bonus: 11000, 
      perks: 'Housing stipend', 
      accepted: true,
      applicationDate: 'July 29, 2024',
      interviewDate: 'August 26, 2024',
      offerDate: 'September 12, 2024',
      responseDate: 'September 20, 2024',
      interviewProcess: '2 rounds: Video interview, In-person callback',
      interviewFormat: 'Mix of behavioral and hypothetical scenarios. Asked about ethical dilemmas.',
      additionalNotes: 'LA office culture is slightly more relaxed than NYC but still intense work.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'Chicago, IL', 
      salary: 225000, 
      bonus: 11000, 
      perks: 'Relocation assistance', 
      accepted: false,
      applicationDate: 'July 31, 2024',
      interviewDate: 'August 28, 2024',
      offerDate: 'September 14, 2024',
      responseDate: 'September 22, 2024',
      interviewProcess: '3 rounds: Phone, Video panel, Callback',
      interviewFormat: 'Standard BigLaw interview. Focus on grades and law review experience.',
      additionalNotes: 'Declined due to concerns about work-life balance based on associate feedback.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 11000, 
      perks: 'Housing support', 
      accepted: true,
      applicationDate: 'August 2, 2024',
      interviewDate: 'August 30, 2024',
      offerDate: 'September 16, 2024',
      responseDate: 'September 24, 2024',
      interviewProcess: '2 rounds: Screening, Callback with M&A group',
      interviewFormat: 'Very thorough. Asked detailed questions about every line on resume.',
      additionalNotes: 'Recruiting coordinator was extremely helpful throughout process.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 6, 
      location: 'Chicago, IL', 
      salary: 225000, 
      bonus: 11000, 
      perks: 'Full relocation support', 
      accepted: true,
      applicationDate: 'August 4, 2024',
      interviewDate: 'September 1, 2024',
      offerDate: 'September 18, 2024',
      responseDate: 'September 26, 2024',
      interviewProcess: '4 rounds: Coffee chat, Phone interview, Video panel, Final callback',
      interviewFormat: 'Long process but very thorough. Got to meet lots of people across practice groups.',
      additionalNotes: 'Appreciated the transparency about hours and expectations.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'Wachtell, Lipton, Rosen & Katz': [
    { 
      id: 1, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 18000, 
      perks: 'Housing, meals, transportation', 
      accepted: true,
      applicationDate: 'August 20, 2024',
      interviewDate: 'September 15, 2024',
      offerDate: 'September 28, 2024',
      responseDate: 'October 5, 2024',
      interviewProcess: '3 rounds: Phone screen, Associate interview, Full partner callback (8 partners)',
      interviewFormat: 'Extremely rigorous. Technical questions on corporate law, hypothetical deal scenarios, ethics questions.',
      additionalNotes: 'Most intense interview process but also most rewarding. You know immediately if you got it.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 18000, 
      perks: 'Full housing support, meals', 
      accepted: true,
      applicationDate: 'August 22, 2024',
      interviewDate: 'September 17, 2024',
      offerDate: 'September 30, 2024',
      responseDate: 'October 7, 2024',
      interviewProcess: '2 rounds: Initial interview with 2 partners, Callback with 6 additional partners',
      interviewFormat: 'Intellectual rigor is real. Asked about law review note, specific cases, and legal theory.',
      additionalNotes: 'Small summer class means lots of responsibility and direct partner contact.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 18000, 
      perks: 'All expenses covered', 
      accepted: true,
      applicationDate: 'August 24, 2024',
      interviewDate: 'September 19, 2024',
      offerDate: 'October 2, 2024',
      responseDate: 'October 9, 2024',
      interviewProcess: '4 rounds: Coffee chat, Phone interview, Associate panel, Partner callback',
      interviewFormat: 'Every interview felt like an exam. Partners are brilliant and expect you to be too.',
      additionalNotes: 'Compensation and prestige are unmatched. Worth the grueling hours.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 18000, 
      perks: 'Housing, meals, transportation', 
      accepted: false,
      applicationDate: 'August 26, 2024',
      interviewDate: 'September 21, 2024',
      offerDate: 'October 4, 2024',
      responseDate: 'October 11, 2024',
      interviewProcess: '3 rounds: Screening, Associate interview, Partner callback',
      interviewFormat: 'Challenging but fair. Questions designed to test analytical thinking and composure.',
      additionalNotes: 'Declined for personal reasons but would recommend to anyone serious about elite corporate work.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'Department of Justice': [
    { 
      id: 1, 
      location: 'Washington, DC', 
      salary: 45000, 
      bonus: 0, 
      perks: 'Federal benefits', 
      accepted: true,
      applicationDate: 'June 15, 2024',
      interviewDate: 'July 20, 2024',
      offerDate: 'August 10, 2024',
      responseDate: 'August 18, 2024',
      interviewProcess: '3 rounds: Application review, Phone interview with section chief, In-person interview with team',
      interviewFormat: 'Focus on commitment to public service and specific interest in DOJ\'s mission. Asked about policy views.',
      additionalNotes: 'Meaningful work that impacts real people. Everyone is mission-driven.',
      position: 'Summer Law Clerk',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'Washington, DC', 
      salary: 45000, 
      bonus: 0, 
      perks: 'Federal benefits, housing assistance', 
      accepted: true,
      applicationDate: 'June 18, 2024',
      interviewDate: 'July 22, 2024',
      offerDate: 'August 12, 2024',
      responseDate: 'August 20, 2024',
      interviewProcess: '2 rounds: Phone screen, Panel interview with 4 attorneys',
      interviewFormat: 'Questions about criminal law knowledge and trial experience. Discussion of courtroom interest.',
      additionalNotes: 'Criminal Division has incredible litigation opportunities. Real trial experience as a summer.',
      position: 'Summer Law Clerk',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'New York, NY', 
      salary: 45000, 
      bonus: 0, 
      perks: 'Federal benefits', 
      accepted: true,
      applicationDate: 'June 20, 2024',
      interviewDate: 'July 24, 2024',
      offerDate: 'August 14, 2024',
      responseDate: 'August 22, 2024',
      interviewProcess: '3 rounds: Application screening, Phone interview, In-person interview',
      interviewFormat: 'Mix of technical legal questions and discussion of public interest commitment.',
      additionalNotes: 'SDNY office is prestigious and handles high-profile cases. Great launching pad for career.',
      position: 'Summer Law Clerk',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'San Francisco, CA', 
      salary: 45000, 
      bonus: 0, 
      perks: 'Federal benefits, relocation', 
      accepted: false,
      applicationDate: 'June 22, 2024',
      interviewDate: 'July 26, 2024',
      offerDate: 'August 16, 2024',
      responseDate: 'August 24, 2024',
      interviewProcess: '2 rounds: Phone interview, Video panel',
      interviewFormat: 'Standard public interest interview. Focus on long-term career goals.',
      additionalNotes: 'Chose private sector for loan repayment reasons but great opportunity.',
      position: 'Summer Law Clerk',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'Washington, DC', 
      salary: 45000, 
      bonus: 0, 
      perks: 'Federal benefits package', 
      accepted: true,
      applicationDate: 'June 24, 2024',
      interviewDate: 'July 28, 2024',
      offerDate: 'August 18, 2024',
      responseDate: 'August 26, 2024',
      interviewProcess: '3 rounds: Written application, Phone screen, Full-day interview',
      interviewFormat: 'Writing sample was heavily scrutinized. In-person interview covered policy interests and legal philosophy.',
      additionalNotes: 'Civil Rights Division is doing incredible work. Fulfilling and impactful.',
      position: 'Summer Law Clerk',
      classYear: '2L'
    },
  ],
  'Paul, Weiss': [
    { 
      id: 1, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 14000, 
      perks: 'Full housing, meals, transportation', 
      accepted: true,
      applicationDate: 'August 5, 2024',
      interviewDate: 'September 1, 2024',
      offerDate: 'September 15, 2024',
      responseDate: 'September 23, 2024',
      interviewProcess: '2 rounds: Phone screen, Callback with 5 partners and associates',
      interviewFormat: 'Conversational but substantive. Asked about specific experiences and how I handled challenges.',
      additionalNotes: 'Diverse and inclusive culture. Felt welcomed immediately.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 14000, 
      perks: 'Housing stipend, meals', 
      accepted: true,
      applicationDate: 'August 7, 2024',
      interviewDate: 'September 3, 2024',
      offerDate: 'September 17, 2024',
      responseDate: 'September 25, 2024',
      interviewProcess: '3 rounds: Initial interview, Practice group meeting, Final callback',
      interviewFormat: 'Focus on fit with firm culture. Asked about teamwork and collaboration style.',
      additionalNotes: 'Litigation department is world-class. Associates are incredibly smart and humble.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 14000, 
      perks: 'Comprehensive benefits', 
      accepted: true,
      applicationDate: 'August 9, 2024',
      interviewDate: 'September 5, 2024',
      offerDate: 'September 19, 2024',
      responseDate: 'September 27, 2024',
      interviewProcess: '2 rounds: Video interview, In-person callback',
      interviewFormat: 'Mix of personal and professional questions. Genuine interest in getting to know candidates.',
      additionalNotes: 'Pro bono culture is strong. Firm really walks the walk on social justice.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 4, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 14000, 
      perks: 'Housing and meals covered', 
      accepted: false,
      applicationDate: 'August 11, 2024',
      interviewDate: 'September 7, 2024',
      offerDate: 'September 21, 2024',
      responseDate: 'September 29, 2024',
      interviewProcess: '3 rounds: Phone, Associate panel, Partner callback',
      interviewFormat: 'Standard interview process. Questions about resume and career interests.',
      additionalNotes: 'Chose another firm for practice area reasons but loved the people here.',
      position: 'Summer Associate',
      classYear: '2L'
    },
    { 
      id: 5, 
      location: 'New York, NY', 
      salary: 225000, 
      bonus: 14000, 
      perks: 'Full support package', 
      accepted: true,
      applicationDate: 'August 13, 2024',
      interviewDate: 'September 9, 2024',
      offerDate: 'September 23, 2024',
      responseDate: 'October 1, 2024',
      interviewProcess: '4 rounds: Coffee chat, Phone screen, Video panel, Final callback',
      interviewFormat: 'Thorough but friendly. Each round built on the previous one.',
      additionalNotes: 'Mentorship program pairs each summer with partner and senior associate. Great support.',
      position: 'Summer Associate',
      classYear: '2L'
    },
  ],
  'McKinsey & Company': [
    { 
      id: 1, 
      location: 'New York, NY', 
      salary: 200000, 
      bonus: 25000, 
      perks: 'Housing, relocation, travel', 
      accepted: true,
      applicationDate: 'July 15, 2024',
      interviewDate: 'August 10, 2024',
      offerDate: 'August 25, 2024',
      responseDate: 'September 2, 2024',
      interviewProcess: '3 rounds: Phone screen, First round (2 case interviews), Final round (3 case interviews)',
      interviewFormat: 'Heavy emphasis on case interviews. Market sizing, profitability, M&A strategy cases.',
      additionalNotes: 'Consulting interviews are different beast. Practice cases extensively beforehand.',
      position: 'Summer Business Analyst',
      classYear: 'JD/MBA 2L'
    },
    { 
      id: 2, 
      location: 'San Francisco, CA', 
      salary: 200000, 
      bonus: 25000, 
      perks: 'Housing, relocation', 
      accepted: true,
      applicationDate: 'July 17, 2024',
      interviewDate: 'August 12, 2024',
      offerDate: 'August 27, 2024',
      responseDate: 'September 4, 2024',
      interviewProcess: '2 rounds: First round (2 cases), Final round (2 cases + behavioral)',
      interviewFormat: 'Case interviews plus behavioral fit questions. Asked about leadership and teamwork.',
      additionalNotes: 'SF office focuses on tech clients. Great if you\'re interested in that sector.',
      position: 'Summer Business Analyst',
      classYear: 'JD/MBA 2L'
    },
    { 
      id: 3, 
      location: 'New York, NY', 
      salary: 200000, 
      bonus: 25000, 
      perks: 'Full benefits package', 
      accepted: true,
      applicationDate: 'July 19, 2024',
      interviewDate: 'August 14, 2024',
      offerDate: 'August 29, 2024',
      responseDate: 'September 6, 2024',
      interviewProcess: '3 rounds: Phone screen, First round interviews, Final round interviews',
      interviewFormat: 'Case interviews test structured thinking and business acumen. Be ready for math.',
      additionalNotes: 'Training program is excellent. Ramp-up support for case interviews and consulting skills.',
      position: 'Summer Business Analyst',
      classYear: 'JD/MBA 2L'
    },
    { 
      id: 4, 
      location: 'San Francisco, CA', 
      salary: 200000, 
      bonus: 25000, 
      perks: 'Housing support', 
      accepted: false,
      applicationDate: 'July 21, 2024',
      interviewDate: 'August 16, 2024',
      offerDate: 'August 31, 2024',
      responseDate: 'September 8, 2024',
      interviewProcess: '3 rounds: Application, First round, Final round',
      interviewFormat: 'Standard McKinsey case format. Interviewers were helpful and collaborative.',
      additionalNotes: 'Chose legal career path but McKinsey was incredible opportunity.',
      position: 'Summer Business Analyst',
      classYear: 'JD/MBA 2L'
    },
  ],
  'ACLU': [
    { 
      id: 1, 
      location: 'Washington, DC', 
      salary: 60000, 
      bonus: 0, 
      perks: 'Public interest benefits', 
      accepted: true,
      applicationDate: 'May 20, 2024',
      interviewDate: 'June 25, 2024',
      offerDate: 'July 15, 2024',
      responseDate: 'July 23, 2024',
      interviewProcess: '3 rounds: Application review, Phone interview, In-person panel interview',
      interviewFormat: 'Questions about commitment to civil liberties and specific issue areas. Discussion of past advocacy.',
      additionalNotes: 'Most meaningful work I could imagine. Everyone is passionate about the mission.',
      position: 'Summer Legal Fellow',
      classYear: '2L'
    },
    { 
      id: 2, 
      location: 'Washington, DC', 
      salary: 60000, 
      bonus: 0, 
      perks: 'Loan forgiveness program', 
      accepted: true,
      applicationDate: 'May 22, 2024',
      interviewDate: 'June 27, 2024',
      offerDate: 'July 17, 2024',
      responseDate: 'July 25, 2024',
      interviewProcess: '2 rounds: Phone screen, Final interview with legal team',
      interviewFormat: 'Deep dive into legal interests and social justice commitment. Asked about specific cases.',
      additionalNotes: 'Working on voting rights and criminal justice reform. Incredible impact.',
      position: 'Summer Legal Fellow',
      classYear: '2L'
    },
    { 
      id: 3, 
      location: 'Washington, DC', 
      salary: 60000, 
      bonus: 0, 
      perks: 'Public service benefits', 
      accepted: true,
      applicationDate: 'May 24, 2024',
      interviewDate: 'June 29, 2024',
      offerDate: 'July 19, 2024',
      responseDate: 'July 27, 2024',
      interviewProcess: '3 rounds: Application, Phone interview, In-person interview with multiple staff attorneys',
      interviewFormat: 'Substantive discussion of civil rights law. Asked about legal writing and research skills.',
      additionalNotes: 'LRAP and PSLF make the salary difference manageable. Worth it for the experience.',
      position: 'Summer Legal Fellow',
      classYear: '2L'
    },
  ]
};